const fs = require('fs');
let src = fs.readFileSync('data-core.js', 'utf8');

const conceptsMatch = src.match(/concepts:\s*\{/);
const startIdx = src.indexOf('{', conceptsMatch.index);
let depth = 0, endIdx = -1;
for (let i = startIdx; i < src.length; i++) {
  if (src[i] === '{') depth++;
  if (src[i] === '}') { depth--; if (depth === 0) { endIdx = i; break; } }
}
eval('var concepts = ' + src.substring(startIdx, endIdx + 1));

const newConcepts = {
  // ═══ NATURE (expand to ~140+) ═══
  "ash_tree": { c: ["ash","bark","forest","leaf","tree","wood"], g: "nature" },
  "birch_bark": { c: ["birch","bark","paper","tree","white"], g: "nature" },
  "canopy": { c: ["forest","green","leaf","shade","tree"], g: "nature" },
  "clearing": { c: ["forest","grass","light","meadow","sun"], g: "nature" },
  "driftwood": { c: ["beach","ocean","sand","water","wood"], g: "nature" },
  "fir": { c: ["cone","forest","green","pine","tree","winter","wood"], g: "nature" },
  "glade": { c: ["clearing","deer","forest","green","light","meadow"], g: "nature" },
  "heath": { c: ["bush","field","flower","moor","shrub","wild"], g: "nature" },
  "hollow": { c: ["cave","dark","owl","tree","trunk"], g: "nature" },
  "husk": { c: ["corn","dry","grain","seed","shell"], g: "nature" },
  "log": { c: ["cabin","fire","forest","timber","tree","wood"], g: "nature" },
  "mangrove": { c: ["coast","fish","root","salt","swamp","tree","water"], g: "nature" },
  "moor": { c: ["bog","cold","fog","heath","wind","wolf"], g: "nature" },
  "oasis_palm": { c: ["desert","oasis","palm","sand","water"], g: "nature" },
  "petal": { c: ["blossom","flower","fragrance","pollen","rose","soft"], g: "nature" },
  "pinecone": { c: ["cone","fir","forest","pine","seed","squirrel","tree"], g: "nature" },
  "pollen": { c: ["bee","bloom","flower","spring","wind","yellow"], g: "nature" },
  "prairie_grass": { c: ["bison","field","grass","plain","prairie","wind"], g: "nature" },
  "reef_coral": { c: ["coral","fish","ocean","reef","water"], g: "nature" },
  "sap": { c: ["amber","maple","pine","sticky","sweet","tree"], g: "nature" },
  "sequoia": { c: ["bark","giant","tall","tree","wood"], g: "nature" },
  "stump": { c: ["axe","log","ring","tree","wood"], g: "nature" },
  "thatch": { c: ["grass","hay","roof","straw","village"], g: "nature" },
  "thistle": { c: ["field","flower","purple","sharp","thorn","wild"], g: "nature" },
  "timber_log": { c: ["axe","build","log","lumberjack","timber","tree","wood"], g: "nature" },
  "twig": { c: ["bird","branch","nest","snap","thin","tree","wood"], g: "nature" },
  "undergrowth": { c: ["bush","dark","fern","forest","green","moss","shrub"], g: "nature" },
  "wildflower": { c: ["bloom","color","field","meadow","petal","spring","wild"], g: "nature" },
  "copse": { c: ["birch","grove","small","tree","wood"], g: "nature" },
  "dell": { c: ["brook","flower","green","meadow","valley"], g: "nature" },
  "estuary": { c: ["delta","fish","ocean","river","salt","water"], g: "nature" },
  "fjord_water": { c: ["cliff","cold","fjord","ice","mountain","water"], g: "nature" },
  "frond": { c: ["fern","green","leaf","palm","tree"], g: "nature" },
  "gorge_river": { c: ["canyon","cliff","gorge","river","rock","water"], g: "nature" },
  "gulch": { c: ["canyon","desert","dry","gorge","rock","sand"], g: "nature" },
  "hillock": { c: ["earth","grass","hill","meadow","slope"], g: "nature" },
  "knoll": { c: ["grass","green","hill","rise","slope"], g: "nature" },
  "lichen_rock": { c: ["green","lichen","moss","rock","stone"], g: "nature" },
  "mesa": { c: ["canyon","desert","flat","plateau","rock","sand"], g: "nature" },
  "rapids": { c: ["foam","river","rock","rush","water","white"], g: "nature" },
  "ravine": { c: ["bridge","cliff","dark","deep","gorge","river","rock"], g: "nature" },
  "shoal": { c: ["fish","ocean","reef","sand","shallow","water"], g: "nature" },
  "tor": { c: ["cliff","granite","moor","rock","stone","wind"], g: "nature" },
  "tributary": { c: ["brook","creek","flow","river","stream","water"], g: "nature" },

  // ═══ ANIMALS (expand to ~180+) ═══
  "albatross": { c: ["bird","fly","ocean","sail","storm","wave","wind","wing"], g: "animals" },
  "alpaca": { c: ["fur","llama","mountain","soft","wool"], g: "animals" },
  "anchovy": { c: ["fish","ocean","salt","sea","small","swim"], g: "animals" },
  "antelope": { c: ["dash","deer","fast","grasshopper","horn","run","savanna","swift"], g: "animals" },
  "armadillo": { c: ["armor","burrow","dig","earth","shell"], g: "animals" },
  "barnacle": { c: ["boat","cling","ocean","rock","shell","ship","water"], g: "animals" },
  "barracuda": { c: ["fast","fish","hunt","ocean","sharp","swim","teeth"], g: "animals" },
  "beetle": { c: ["black","bug","crawl","earth","garden","shell","wood"], g: "animals" },
  "beluga": { c: ["cold","ice","ocean","sing","swim","whale","white"], g: "animals" },
  "bison_bull": { c: ["bison","buffalo","grass","horn","plain","prairie","wild"], g: "animals" },
  "bluejay": { c: ["bird","blue","feather","fly","jay","song","tree","wing"], g: "animals" },
  "bobcat": { c: ["cat","claw","forest","hunt","prowl","wild"], g: "animals" },
  "bullfrog": { c: ["frog","green","jump","pond","rain","sing","water"], g: "animals" },
  "cardinal": { c: ["bird","fly","red","sing","song","tree","winter"], g: "animals" },
  "caribou": { c: ["cold","elk","horn","ice","migrate","snow","tundra"], g: "animals" },
  "catfish": { c: ["fish","mud","pond","river","swim","water","whisker"], g: "animals" },
  "centipede": { c: ["crawl","dark","earth","fast","leg","poison"], g: "animals" },
  "chipmunk": { c: ["acorn","climb","forest","nut","squirrel","tree"], g: "animals" },
  "cicada": { c: ["buzz","hot","insect","sing","summer","tree"], g: "animals" },
  "clam_shell": { c: ["clam","ocean","pearl","sand","shell","water"], g: "animals" },
  "cormorant": { c: ["bird","coast","dive","fish","ocean","water","wing"], g: "animals" },
  "coyote_wild": { c: ["coyote","desert","howl","hunt","moon","night","wild","wolf"], g: "animals" },
  "crayfish": { c: ["claw","creek","river","shell","water"], g: "animals" },
  "cricket": { c: ["chirp","grass","green","hop","night","sing","summer"], g: "animals" },
  "dove_white": { c: ["bird","dove","feather","fly","hope","peace","white","wing"], g: "animals" },
  "emu": { c: ["bird","desert","fast","feather","run","sand"], g: "animals" },
  "ermine": { c: ["cold","fur","snow","white","winter"], g: "animals" },
  "ferret": { c: ["burrow","dig","fast","fur","hunt","tunnel"], g: "animals" },
  "fireant": { c: ["ant","bite","earth","fire","red","sting","swarm"], g: "animals" },
  "flounder": { c: ["fish","flat","ocean","sand","swim","water"], g: "animals" },
  "goose": { c: ["bird","egg","farm","feather","fly","honk","lake","wing"], g: "animals" },
  "gorilla_ape": { c: ["ape","chest","forest","gorilla","jungle","strong","tree"], g: "animals" },
  "grouse": { c: ["bird","bush","feather","forest","hunt","moor"], g: "animals" },
  "gull": { c: ["beach","bird","coast","cry","fish","fly","ocean","wave","wing"], g: "animals" },
  "hamster": { c: ["cage","fur","pet","run","small","wheel"], g: "animals" },
  "hatchling": { c: ["bird","chick","egg","nest","small","spring"], g: "animals" },
  "hermitcrab": { c: ["beach","claw","crawl","sand","shell","small"], g: "animals" },
  "hornet": { c: ["buzz","fly","nest","sting","swarm","wasp","yellow"], g: "animals" },
  "ibis": { c: ["beak","bird","marsh","wade","water","wetland","white"], g: "animals" },
  "jackal_wild": { c: ["desert","howl","hunt","jackal","night","pack","sand","wild"], g: "animals" },
  "kestrel": { c: ["bird","falcon","fast","fly","hawk","hunt","sky","wing"], g: "animals" },
  "ladybug_red": { c: ["garden","ladybug","leaf","red","small","spot","wing"], g: "animals" },
  "lamprey": { c: ["dark","eel","river","swim","teeth","water"], g: "animals" },
  "leech": { c: ["blood","dark","mud","swamp","water","worm"], g: "animals" },
  "loon": { c: ["bird","cry","dive","fish","lake","night","swim","water"], g: "animals" },
  "manatee": { c: ["gentle","ocean","slow","swim","warm","water"], g: "animals" },
  "mantis": { c: ["bug","green","hunt","insect","leaf","pray","swift"], g: "animals" },
  "marten": { c: ["climb","forest","fur","hunt","pine","tree"], g: "animals" },
  "mink": { c: ["coat","cold","dark","fur","river","water"], g: "animals" },
  "mockingbird": { c: ["bird","mimic","night","sing","song","tree","voice"], g: "animals" },
  "mongoose": { c: ["cobra","fast","fight","hunt","snake","swift"], g: "animals" },
  "mosquito": { c: ["bite","blood","buzz","fly","night","swamp","water"], g: "animals" },
  "mussel": { c: ["clam","ocean","rock","salt","shell","water"], g: "animals" },
  "narwhal": { c: ["cold","horn","ice","ocean","swim","tusk","whale"], g: "animals" },
  "newt": { c: ["damp","green","pond","salamander","swim","water"], g: "animals" },
  "opossum": { c: ["climb","dark","night","play","tail","tree"], g: "animals" },
  "oriole": { c: ["bird","fly","gold","nest","orange","sing","tree"], g: "animals" },
  "osprey_fish": { c: ["bird","dive","eagle","fish","fly","hunt","osprey","river","water","wing"], g: "animals" },
  "pangolin": { c: ["armor","claw","dig","earth","roll","scale","shell"], g: "animals" },
  "parakeet": { c: ["bird","bright","cage","color","feather","fly","green","sing"], g: "animals" },
  "partridge": { c: ["bird","bush","farm","feather","hunt","pear","tree"], g: "animals" },
  "pelican_bird": { c: ["beak","bird","coast","dive","fish","fly","ocean","pelican","water"], g: "animals" },
  "perch": { c: ["fish","lake","pond","river","swim","water"], g: "animals" },
  "pheasant": { c: ["bird","color","farm","feather","field","fly","gold","hunt"], g: "animals" },
  "platypus": { c: ["beak","duck","egg","fur","poison","swim","water"], g: "animals" },
  "plover": { c: ["beach","bird","coast","fly","nest","sand","shore","wave"], g: "animals" },
  "porcupine_quill": { c: ["forest","needle","porcupine","quill","sharp","spine","tree"], g: "animals" },
  "prawn": { c: ["cook","fish","ocean","pink","salt","shell","swim","water"], g: "animals" },
  "puffin": { c: ["beak","bird","cliff","coast","cold","fish","fly","ocean","swim"], g: "animals" },
  "python": { c: ["coil","crush","forest","jungle","scale","snake","squeeze","tree"], g: "animals" },
  "quetzal": { c: ["bird","bright","feather","fly","green","jungle","tail"], g: "animals" },
  "rattlesnake": { c: ["bite","desert","fang","poison","rattle","sand","snake","venom"], g: "animals" },
  "ray": { c: ["flat","fly","glide","ocean","sand","sting","swim","water","wing"], g: "animals" },
  "roadrunner": { c: ["bird","dash","desert","fast","run","sand","swift"], g: "animals" },
  "sandpiper": { c: ["beach","bird","coast","run","sand","shore","small","wave","water"], g: "animals" },
  "sawfish": { c: ["fish","nose","ocean","saw","sharp","swim","water"], g: "animals" },
  "scarab": { c: ["beetle","desert","earth","egypt","gold","sand","sun"], g: "animals" },
  "shrimp": { c: ["cook","fish","ocean","pink","salt","shell","small","swim","water"], g: "animals" },
  "skink": { c: ["crawl","lizard","scale","sun","tail","warm"], g: "animals" },
  "skylark": { c: ["bird","dawn","fly","morning","sing","sky","song","spring","wing"], g: "animals" },
  "sloth": { c: ["climb","forest","fur","green","hang","slow","sleep","tree"], g: "animals" },
  "snipe": { c: ["bird","bog","fly","hunt","marsh","mud","wetland"], g: "animals" },
  "sparrow_bird": { c: ["bird","brown","city","fly","nest","sing","small","sparrow","tree","wing"], g: "animals" },
  "sponge": { c: ["coral","ocean","reef","soft","water"], g: "animals" },
  "squid_deep": { c: ["dark","deep","ink","ocean","squid","swim","tentacle","water"], g: "animals" },
  "stallion": { c: ["fast","gallop","horse","mane","ride","run","strong","wild"], g: "animals" },
  "starfish": { c: ["beach","coral","ocean","reef","sand","shell","star","water"], g: "animals" },
  "stingray": { c: ["flat","ocean","sand","sting","swim","tail","water"], g: "animals" },
  "stoat": { c: ["cold","ermine","fast","fur","hunt","snow","white","winter"], g: "animals" },
  "sturgeon": { c: ["ancient","egg","fish","large","old","river","swim","water"], g: "animals" },
  "swallow": { c: ["bird","fast","fly","migrate","sky","spring","summer","swift","wing"], g: "animals" },
  "swift_bird": { c: ["bird","fast","fly","sky","small","summer","swift","wind","wing"], g: "animals" },
  "swordfish": { c: ["fast","fish","ocean","sharp","swim","sword","water"], g: "animals" },
  "tapir": { c: ["forest","jungle","mud","nose","river","swim","water"], g: "animals" },
  "termite": { c: ["build","colony","earth","eat","mound","nest","wood"], g: "animals" },
  "tern": { c: ["beach","bird","coast","dive","fish","fly","ocean","small","white"], g: "animals" },
  "terrapin": { c: ["marsh","pond","shell","swim","turtle","water"], g: "animals" },
  "tick": { c: ["bite","blood","bush","grass","small","wood"], g: "animals" },
  "vole": { c: ["burrow","earth","field","grass","mouse","small","tunnel"], g: "animals" },
  "warbler": { c: ["bird","bush","forest","sing","small","song","spring","tree"], g: "animals" },
  "warthog": { c: ["boar","dig","grass","mud","savanna","tusk","wild"], g: "animals" },
  "wasp_sting": { c: ["buzz","fly","nest","sting","swarm","wasp","yellow"], g: "animals" },
  "woodpecker": { c: ["beak","bird","drum","forest","hammer","hole","tree","wood"], g: "animals" },
  "wren": { c: ["bird","bush","nest","sing","small","song","tree"], g: "animals" },
  "yak": { c: ["cold","fur","horn","mountain","snow","strong","wool"], g: "animals" },

  // ═══ OBJECTS (expand to ~190+) ═══
  "abacus": { c: ["bead","count","math","old","wood"], g: "objects" },
  "accordion": { c: ["air","dance","fold","music","play","squeeze"], g: "objects" },
  "amulet": { c: ["charm","gold","magic","protect","silver","spirit"], g: "objects" },
  "apron": { c: ["baker","chef","cook","kitchen","tie"], g: "objects" },
  "bandage": { c: ["blood","cut","heal","white","wound","wrap"], g: "objects" },
  "banner": { c: ["castle","cloth","flag","hang","knight","war","wave","wind"], g: "objects" },
  "bellows": { c: ["air","blow","fire","forge","hot","smith"], g: "objects" },
  "blade": { c: ["cut","edge","knife","sharp","steel","sword"], g: "objects" },
  "bolt_iron": { c: ["bolt","iron","lock","metal","nut","screw","steel","tight"], g: "objects" },
  "brazier": { c: ["burn","coal","fire","glow","heat","hot","iron","warm"], g: "objects" },
  "buckle": { c: ["belt","boot","brass","clasp","leather","metal","strap"], g: "objects" },
  "candlestick": { c: ["brass","candle","flame","gold","light","wax"], g: "objects" },
  "chalice": { c: ["cup","drink","gem","goblet","gold","silver","wine"], g: "objects" },
  "cloak": { c: ["cloth","cold","dark","hide","shadow","warm","wind","wool"], g: "objects" },
  "cobblestone": { c: ["brick","gray","path","road","stone","street","walk"], g: "objects" },
  "cog": { c: ["clock","gear","iron","machine","metal","spin","turn","wheel"], g: "objects" },
  "crucible": { c: ["fire","forge","gold","heat","hot","melt","metal","pour"], g: "objects" },
  "decanter": { c: ["crystal","glass","pour","red","wine"], g: "objects" },
  "emblem": { c: ["banner","crown","flag","gold","honor","knight","shield","symbol"], g: "objects" },
  "flail": { c: ["chain","farm","grain","hit","iron","swing","weapon","wheat"], g: "objects" },
  "flask_glass": { c: ["drink","flask","glass","liquid","potion","water"], g: "objects" },
  "gauntlet": { c: ["armor","fight","glove","hand","iron","knight","steel","war"], g: "objects" },
  "goblet_gold": { c: ["cup","drink","feast","gem","goblet","gold","king","wine"], g: "objects" },
  "gong": { c: ["bell","brass","hit","loud","metal","monk","ring","sound","temple"], g: "objects" },
  "grail": { c: ["chalice","cup","gold","holy","knight","legend","quest","sacred"], g: "objects" },
  "harpoon": { c: ["hunt","iron","ocean","rope","sharp","spear","whale","water"], g: "objects" },
  "helm": { c: ["armor","head","helmet","iron","knight","shield","steel","war"], g: "objects" },
  "hourglass_sand": { c: ["glass","hourglass","sand","slow","time","turn","wait"], g: "objects" },
  "inkpot": { c: ["black","ink","pen","quill","write"], g: "objects" },
  "kettle_pot": { c: ["boil","copper","fire","hot","kettle","pour","steam","tea","water"], g: "objects" },
  "latch": { c: ["bolt","click","door","gate","iron","lock","open","shut"], g: "objects" },
  "lens": { c: ["eye","focus","glass","light","magnify","see","telescope"], g: "objects" },
  "lockbox": { c: ["gold","iron","key","lock","safe","secret","treasure"], g: "objects" },
  "mace": { c: ["crush","fight","hit","iron","knight","metal","spike","war","weapon"], g: "objects" },
  "manacle": { c: ["chain","hand","iron","lock","prison","wrist"], g: "objects" },
  "mortar_pestle": { c: ["bowl","crush","grind","herb","mortar","spice","stone"], g: "objects" },
  "necklace": { c: ["bead","chain","gem","gold","jewel","neck","pearl","silver","string"], g: "objects" },
  "oar_boat": { c: ["boat","oar","paddle","pull","river","row","water","wood"], g: "objects" },
  "pendant": { c: ["chain","gem","gold","hang","jewel","necklace","neck","silver"], g: "objects" },
  "pestle": { c: ["bowl","crush","grind","herb","mortar","smooth","spice","stone"], g: "objects" },
  "pike": { c: ["long","point","sharp","soldier","spear","steel","war","weapon"], g: "objects" },
  "platter": { c: ["feast","flat","food","gold","plate","serve","silver","wood"], g: "objects" },
  "plow": { c: ["dirt","earth","farm","field","horse","iron","ox","soil"], g: "objects" },
  "quill_pen": { c: ["bird","feather","ink","pen","quill","write"], g: "objects" },
  "rudder": { c: ["boat","guide","ocean","sail","ship","steer","water","wood"], g: "objects" },
  "saddle_horse": { c: ["horse","leather","ride","saddle","strap","stirrup"], g: "objects" },
  "scabbard": { c: ["belt","blade","knight","leather","sheath","sword","weapon"], g: "objects" },
  "scepter": { c: ["crown","gem","gold","king","power","queen","rule","throne"], g: "objects" },
  "scroll_paper": { c: ["ink","old","paper","read","scroll","write"], g: "objects" },
  "shackle": { c: ["chain","iron","lock","prison","wrist"], g: "objects" },
  "shuttle": { c: ["loom","thread","weave","weaver","wool"], g: "objects" },
  "sieve": { c: ["drain","flour","grain","hole","pour","separate","small","water"], g: "objects" },
  "sledge": { c: ["cold","dog","ice","pull","ride","snow","wood"], g: "objects" },
  "snare": { c: ["catch","drum","hunt","loop","rabbit","rope","trap","wire"], g: "objects" },
  "spindle": { c: ["cotton","needle","sleep","spin","thread","wheel","wool"], g: "objects" },
  "sundial": { c: ["circle","garden","hour","shadow","stone","sun","time"], g: "objects" },
  "talisman": { c: ["amulet","charm","luck","magic","protect","spirit","stone"], g: "objects" },
  "tankard": { c: ["ale","copper","drink","foam","metal","mug","tavern"], g: "objects" },
  "thimble": { c: ["finger","metal","needle","protect","sew","small","thread"], g: "objects" },
  "tome": { c: ["book","dust","knowledge","old","page","read","scroll","wisdom","write"], g: "objects" },
  "torch_fire": { c: ["burn","cave","dark","fire","flame","light","night","torch","wood"], g: "objects" },
  "totem": { c: ["animal","carve","eagle","pole","spirit","tree","wolf","wood"], g: "objects" },
  "trident": { c: ["fish","fork","ocean","point","sea","sharp","spear","water","weapon"], g: "objects" },
  "trinket": { c: ["bead","charm","gem","gold","jewel","ring","small","treasure"], g: "objects" },
  "trowel": { c: ["brick","build","dig","garden","mason","mortar","plant","wall"], g: "objects" },
  "tuning_fork": { c: ["metal","note","ring","sound","tune","vibrate"], g: "objects" },
  "urn": { c: ["ash","clay","dust","gold","old","pot","pottery","vase"], g: "objects" },
  "weathervane": { c: ["iron","metal","north","roof","rooster","spin","tower","wind"], g: "objects" },
  "whetstone": { c: ["blade","edge","grind","knife","sharp","smooth","stone","sword"], g: "objects" },

  // ═══ ABSTRACT (expand to ~130+) ═══
  "alchemy": { c: ["alchemist","fire","gold","lead","magic","mercury","philosopher","transform"], g: "abstract" },
  "blaze": { c: ["burn","fire","flame","gold","heat","hot","light","orange","red","wild"], g: "abstract" },
  "blessing": { c: ["angel","gift","grace","heal","holy","joy","light","priest","sacred"], g: "abstract" },
  "burden": { c: ["carry","heavy","mountain","shoulder","stone","strong","weight"], g: "abstract" },
  "catalyst": { c: ["change","fast","fire","spark","start","transform"], g: "abstract" },
  "cipher": { c: ["code","enigma","hide","key","lock","mystery","riddle","secret","write"], g: "abstract" },
  "conquest": { c: ["battle","castle","crown","king","sword","victory","war","warrior"], g: "abstract" },
  "conundrum": { c: ["enigma","maze","mystery","puzzle","riddle","solve","think"], g: "abstract" },
  "creed": { c: ["faith","honor","oath","priest","sacred","soul","temple","truth"], g: "abstract" },
  "cryptic": { c: ["code","dark","enigma","hide","mystery","riddle","secret","shadow"], g: "abstract" },
  "curse": { c: ["dark","demon","evil","magic","shadow","spell","witch"], g: "abstract" },
  "dawn_light": { c: ["dawn","gold","hope","light","morning","rise","sun","warm"], g: "abstract" },
  "dominion": { c: ["castle","crown","king","land","power","rule","throne"], g: "abstract" },
  "duality": { c: ["balance","dark","light","mirror","moon","shadow","sun","two"], g: "abstract" },
  "eclipse_shadow": { c: ["dark","eclipse","moon","shadow","sun"], g: "abstract" },
  "elegy": { c: ["death","grief","memory","mourn","poem","sad","song","sorrow","tear"], g: "abstract" },
  "epoch": { c: ["age","ancient","era","history","long","old","time"], g: "abstract" },
  "essence": { c: ["core","flower","fragrance","origin","pure","soul","spirit","truth"], g: "abstract" },
  "exile": { c: ["alone","cold","desert","far","island","journey","lonely","wander"], g: "abstract" },
  "fable": { c: ["animal","fox","legend","lesson","old","story","tale","wolf","wisdom"], g: "abstract" },
  "folktale": { c: ["fairy","forest","legend","old","story","tale","village","wolf","wisdom"], g: "abstract" },
  "forge_soul": { c: ["courage","fire","forge","hammer","honor","iron","steel","strong","warrior"], g: "abstract" },
  "genesis": { c: ["begin","birth","create","dawn","first","life","origin","spark","start"], g: "abstract" },
  "harbinger": { c: ["come","crow","dark","doom","fate","future","omen","raven","sign"], g: "abstract" },
  "heritage": { c: ["ancestor","blood","family","father","honor","legacy","mother","old","root"], g: "abstract" },
  "hymn_sacred": { c: ["angel","choir","church","hymn","peace","pray","sacred","sing","soul","voice"], g: "abstract" },
  "infinity": { c: ["circle","cosmos","cycle","endless","forever","loop","star","time","universe","void"], g: "abstract" },
  "justice": { c: ["balance","blind","court","honor","judge","law","scale","sword","truth"], g: "abstract" },
  "kinship": { c: ["blood","bond","brother","child","family","father","love","mother","trust"], g: "abstract" },
  "labyrinth_mind": { c: ["dark","enigma","labyrinth","lost","maze","mind","riddle","twist","wander"], g: "abstract" },
  "legacy": { c: ["ancestor","blood","child","crown","family","father","gold","heritage","honor","king","old"], g: "abstract" },
  "lament": { c: ["cry","death","grief","mourn","sad","sorrow","tear","voice","woe"], g: "abstract" },
  "mandate": { c: ["command","crown","duty","honor","king","law","oath","power","rule"], g: "abstract" },
  "nemesis": { c: ["dark","enemy","evil","fate","fight","mirror","rival","shadow","sword","war"], g: "abstract" },
  "nexus": { c: ["bond","bridge","center","connect","core","gate","join","link","web"], g: "abstract" },
  "oblivion": { c: ["abyss","dark","death","empty","forget","nothing","silence","void"], g: "abstract" },
  "omen_dark": { c: ["black","crow","dark","death","doom","eclipse","fate","fear","night","omen","raven","sign"], g: "abstract" },
  "parable": { c: ["fable","lesson","old","seed","story","tale","teach","truth","wisdom"], g: "abstract" },
  "paradox_loop": { c: ["circle","contradiction","enigma","loop","mirror","paradox","puzzle","riddle","time","twist"], g: "abstract" },
  "penance": { c: ["church","guilt","kneel","monk","pain","pray","priest","shame","sin","temple"], g: "abstract" },
  "pinnacle": { c: ["climb","glory","gold","high","mountain","peak","rise","sky","summit","top","triumph"], g: "abstract" },
  "prophecy_dark": { c: ["dark","doom","fate","future","oracle","omen","prophecy","raven","seer","sign","vision"], g: "abstract" },
  "rebirth": { c: ["ash","dawn","fire","life","new","phoenix","rise","spring","start","sun","transform"], g: "abstract" },
  "redemption": { c: ["blood","courage","faith","forgive","grace","heal","hope","light","mercy","save","soul","truth"], g: "abstract" },
  "requiem": { c: ["bell","choir","church","death","elegy","mourn","music","rest","silence","sing","song","soul"], g: "abstract" },
  "reverie": { c: ["calm","cloud","dream","float","mind","peace","silence","sleep","soft","wander"], g: "abstract" },
  "riddle_dark": { c: ["cave","code","dark","enigma","maze","mystery","oracle","riddle","secret","shadow","solve","sphinx"], g: "abstract" },
  "rune": { c: ["ancient","carve","enigma","magic","old","rock","secret","sign","stone","symbol","wizard","write"], g: "abstract" },
  "saga_tale": { c: ["battle","hero","honor","journey","king","legend","saga","song","sword","tale","war","warrior"], g: "abstract" },
  "sanctuary_soul": { c: ["calm","garden","haven","heal","holy","light","peace","quiet","sacred","safe","sanctuary","silence","soul","temple"], g: "abstract" },
  "sentinel": { c: ["castle","eye","gate","guard","knight","night","stand","tower","vigil","wall","watch"], g: "abstract" },
  "solitude": { c: ["alone","calm","cold","desert","island","lonely","moon","mountain","night","peace","quiet","silence","snow","soul","winter"], g: "abstract" },
  "tempest_fury": { c: ["dark","fury","lightning","ocean","rage","rain","roar","storm","tempest","thunder","wave","wild","wind","wrath"], g: "abstract" },
  "threshold": { c: ["begin","bridge","cross","door","edge","enter","gate","pass","start","step"], g: "abstract" },
  "tribute": { c: ["crown","feast","gift","gold","honor","king","memory","offer","tribute","war"], g: "abstract" },
  "vow": { c: ["bond","honor","knight","love","oath","promise","ring","sacred","trust","truth","word"], g: "abstract" },
  "wanderlust": { c: ["explore","far","horizon","journey","map","road","roam","travel","wander","wind","world"], g: "abstract" },
  "zenith_peak": { c: ["climb","gold","high","mountain","peak","pinnacle","rise","sky","star","summit","sun","top","zenith"], g: "abstract" },

  // ═══ EMOTIONS (expand to ~85+) ═══
  "anguish": { c: ["agony","cry","dark","despair","grief","heart","pain","scream","sorrow","tear","torment","woe"], g: "emotions" },
  "aversion": { c: ["cold","disgust","fear","hate","push","reject","turn"], g: "emotions" },
  "bewilderment": { c: ["confuse","fog","lost","maze","puzzle","riddle","surprise"], g: "emotions" },
  "bitterness": { c: ["cold","dark","envy","green","hate","poison","resentment","sour","wormwood"], g: "emotions" },
  "bliss_pure": { c: ["bliss","calm","cloud","dream","float","heaven","joy","light","peace","pure","smile","soft","warm"], g: "emotions" },
  "compassion": { c: ["empathy","gentle","hand","heal","heart","hope","kind","love","mercy","soft","warm"], g: "emotions" },
  "defiance": { c: ["brave","courage","fist","fire","lion","rage","rebel","resist","roar","stand","strong","sword"], g: "emotions" },
  "desolation": { c: ["alone","ash","cold","dark","desert","despair","dust","empty","gray","ruin","sand","void","wind","winter"], g: "emotions" },
  "devotion": { c: ["altar","faith","heart","holy","honor","kneel","love","pray","sacred","soul","temple","vow"], g: "emotions" },
  "dismay": { c: ["cold","dark","dread","face","fall","fear","gray","shock","storm"], g: "emotions" },
  "dread_dark": { c: ["abyss","cold","dark","death","deep","doom","dread","fear","gray","night","shadow","void"], g: "emotions" },
  "elation": { c: ["dance","fly","gold","high","joy","laugh","light","peak","rise","sing","smile","soar","sun","warm"], g: "emotions" },
  "exhilaration": { c: ["dash","fast","fly","high","jump","laugh","peak","rise","rush","soar","spark","thrill","wind"], g: "emotions" },
  "fervor": { c: ["blaze","burn","fire","flame","fury","glow","heart","hot","passion","red","zeal"], g: "emotions" },
  "foreboding": { c: ["cloud","cold","crow","dark","doom","dread","fate","fog","gray","night","omen","raven","shadow","storm"], g: "emotions" },
  "glee": { c: ["child","dance","fun","joy","laugh","light","play","sing","smile","warm"], g: "emotions" },
  "gloom_dark": { c: ["cloud","cold","dark","dusk","fog","gloom","gray","mist","night","rain","sad","shadow","winter"], g: "emotions" },
  "grit_courage": { c: ["brave","courage","dust","fight","grind","iron","sand","stone","strong","sword","teeth"], g: "emotions" },
  "grudge": { c: ["anger","bitter","cold","dark","envy","hate","heart","ice","poison","resentment","stone"], g: "emotions" },
  "humility": { c: ["bow","calm","earth","gentle","grace","kneel","low","monk","peace","quiet","small","soft"], g: "emotions" },
  "indignation": { c: ["anger","blaze","burn","fire","fist","hot","rage","red","roar","wrath"], g: "emotions" },
  "loneliness": { c: ["alone","cold","dark","desert","empty","island","lonely","moon","night","rain","silence","snow","void","winter"], g: "emotions" },
  "melancholy_deep": { c: ["autumn","cloud","cold","dark","dusk","fall","fog","gray","leaf","melancholy","moon","rain","shadow","winter","wither"], g: "emotions" },
  "mirth": { c: ["bell","child","dance","feast","fun","joy","laugh","light","play","sing","smile","warm"], g: "emotions" },
  "obsession": { c: ["burn","chain","circle","dark","eye","fire","hunt","loop","madness","mirror","moon","night","pursue"], g: "emotions" },
  "rapture": { c: ["angel","bliss","cloud","dance","ecstasy","fly","gold","heaven","joy","light","sing","soar","sun"], g: "emotions" },
  "regret": { c: ["ache","autumn","cold","dark","fall","gray","heart","memory","rain","shadow","sorrow","tear","wilt","winter"], g: "emotions" },
  "relief": { c: ["breath","calm","exhale","light","peace","rain","rest","sigh","smile","soft","warm","water"], g: "emotions" },
  "resolve": { c: ["brave","courage","fist","fire","grind","iron","mountain","stand","steel","stone","strong","sword","vow","wall"], g: "emotions" },
  "revulsion": { c: ["cold","dark","disgust","green","horror","poison","push","sick","snake","turn","venom"], g: "emotions" },
  "spite": { c: ["bitter","cold","dark","envy","hate","ice","poison","sharp","snake","sting","thorn","venom"], g: "emotions" },
  "suspicion": { c: ["cold","crow","dark","doubt","eye","fog","night","shadow","snake","spider","watch"], g: "emotions" },
  "tenderness": { c: ["baby","blossom","child","flower","gentle","hand","heart","kiss","love","mother","petal","rose","soft","warm"], g: "emotions" },
  "torment_soul": { c: ["agony","burn","chain","cry","dark","demon","fire","pain","scream","soul","torment","wrath"], g: "emotions" },
  "triumph_glory": { c: ["battle","crown","glory","gold","hero","king","light","pride","rise","roar","sun","sword","triumph","war","warrior"], g: "emotions" },
  "unease": { c: ["cold","dark","fog","gray","haze","night","shadow","shiver","silence","spider","still","watch"], g: "emotions" },
  "vengeance": { c: ["blood","burn","dark","death","fire","fury","rage","red","shadow","strike","sword","war","wrath"], g: "emotions" },
  "vigor": { c: ["blood","dash","fast","fire","force","grow","horse","jump","oak","pulse","rise","run","spring","strong","sun","wild"], g: "emotions" },
  "wistfulness": { c: ["autumn","breeze","cloud","dawn","dusk","far","leaf","memory","moon","nostalgia","rain","soft","sunset","wind","yearning"], g: "emotions" },

  // ═══ FOOD (expand to ~110+) ═══
  "ale": { c: ["barley","brewer","drink","foam","gold","grain","mug","tankard","tavern","wheat","yeast"], g: "food" },
  "anise": { c: ["herb","seed","smell","spice","star","sweet","taste"], g: "food" },
  "apricot": { c: ["fruit","gold","jam","juice","orange","soft","summer","sweet","tree"], g: "food" },
  "avocado": { c: ["cream","fruit","green","soft","tree"], g: "food" },
  "basil_herb": { c: ["basil","cook","garden","green","herb","leaf","smell","spice","taste"], g: "food" },
  "blackberry": { c: ["berry","black","bush","dark","jam","juice","purple","summer","sweet","thorn","wild"], g: "food" },
  "bread_loaf": { c: ["baker","bread","crust","dough","flour","grain","oven","slice","wheat","yeast"], g: "food" },
  "brine": { c: ["cook","cucumber","fish","ocean","olive","pickle","preserve","salt","sour","water"], g: "food" },
  "broth_soup": { c: ["bone","broth","cook","garlic","heat","herb","hot","meat","salt","soup","stew","warm"], g: "food" },
  "cardamom": { c: ["green","herb","seed","smell","spice","sweet","tea","warm"], g: "food" },
  "celery": { c: ["cook","crisp","green","leaf","salt","stalk","water"], g: "food" },
  "chestnut": { c: ["autumn","brown","fall","forest","nut","roast","tree","warm","winter","wood"], g: "food" },
  "clove": { c: ["brown","herb","hot","smell","spice","sweet","warm"], g: "food" },
  "cornbread": { c: ["bread","butter","cook","corn","farm","flour","gold","oven","warm","yellow"], g: "food" },
  "coriander": { c: ["cook","green","herb","leaf","seed","smell","spice","taste"], g: "food" },
  "cranberry_fruit": { c: ["berry","bog","cranberry","frost","juice","red","sour","swamp","tart","winter"], g: "food" },
  "cumin": { c: ["cook","earth","hot","seed","smell","spice","warm","yellow"], g: "food" },
  "curd": { c: ["cheese","cream","milk","soft","sour","white"], g: "food" },
  "fennel": { c: ["cook","green","herb","seed","smell","spice","sweet","taste"], g: "food" },
  "feta": { c: ["cheese","cream","goat","milk","olive","salt","white"], g: "food" },
  "gruel": { c: ["grain","hot","oat","poor","thin","warm","water"], g: "food" },
  "guava": { c: ["fruit","green","juice","pink","seed","sweet","tree","tropical"], g: "food" },
  "hazelnut": { c: ["autumn","brown","chocolate","cream","forest","nut","sweet","tree"], g: "food" },
  "horseradish": { c: ["bite","hot","root","sharp","spice","strong","white"], g: "food" },
  "juniper": { c: ["berry","blue","bush","cold","forest","green","pine","spice"], g: "food" },
  "kale": { c: ["bitter","cook","dark","green","leaf","tough"], g: "food" },
  "lard": { c: ["cook","fat","grease","meat","oil","pig","white"], g: "food" },
  "lentil": { c: ["brown","cook","earth","grain","green","seed","soup","stew"], g: "food" },
  "marmalade": { c: ["fruit","jam","lemon","orange","sugar","sweet","toast"], g: "food" },
  "mead": { c: ["drink","feast","gold","honey","sweet","tavern","warm"], g: "food" },
  "molasses": { c: ["brown","dark","slow","sugar","sweet","thick"], g: "food" },
  "mulberry": { c: ["berry","bird","dark","jam","juice","purple","silk","sweet","tree"], g: "food" },
  "mustard": { c: ["hot","sharp","smell","spice","strong","yellow"], g: "food" },
  "nutmeg": { c: ["brown","nut","smell","spice","sweet","warm","winter"], g: "food" },
  "oat": { c: ["bread","farm","field","grain","gruel","harvest","horse","seed","wheat"], g: "food" },
  "parsley": { c: ["cook","garden","green","herb","leaf","smell","taste"], g: "food" },
  "parsnip": { c: ["cook","cream","earth","root","sweet","white","winter"], g: "food" },
  "pastry": { c: ["baker","butter","cream","crust","dough","flour","sweet"], g: "food" },
  "persimmon": { c: ["autumn","fall","fruit","gold","orange","soft","sweet","tree"], g: "food" },
  "pickle": { c: ["brine","cook","cucumber","green","salt","sour","vinegar"], g: "food" },
  "pomegranate": { c: ["blood","fruit","gem","juice","red","ruby","seed","sweet"], g: "food" },
  "porridge": { c: ["grain","gruel","hot","milk","morning","oat","soft","warm"], g: "food" },
  "prune": { c: ["dark","dry","fruit","plum","purple","sweet","wrinkle"], g: "food" },
  "quince": { c: ["autumn","fragrance","fruit","gold","jam","sour","tree","yellow"], g: "food" },
  "radish": { c: ["bite","crisp","earth","garden","pink","red","root","sharp","spice"], g: "food" },
  "rosemary": { c: ["cook","fragrance","garden","green","herb","memory","pine","smell","spice"], g: "food" },
  "saffron": { c: ["cook","flower","gold","precious","red","smell","spice","warm","yellow"], g: "food" },
  "sage": { c: ["cook","garden","gray","green","herb","old","smell","spice","wisdom"], g: "food" },
  "sorrel": { c: ["green","herb","leaf","sour","soup","spring","taste","wild"], g: "food" },
  "tallow": { c: ["burn","candle","fat","flame","light","oil","wax","white"], g: "food" },
  "tamarind": { c: ["brown","fruit","seed","sour","spice","sweet","tree","tropical"], g: "food" },
  "tangerine": { c: ["citrus","fruit","juice","orange","peel","sweet"], g: "food" },
  "turnip": { c: ["cook","earth","farm","root","soil","white","winter"], g: "food" },
  "venison": { c: ["deer","feast","hunt","meat","roast","stag","stew","wild"], g: "food" },
  "vinegar": { c: ["acid","cook","grape","pickle","sharp","sour","wine"], g: "food" },
  "watercress": { c: ["brook","cook","green","leaf","pepper","spring","stream","water"], g: "food" },
  "yam": { c: ["brown","cook","earth","farm","orange","root","sweet","warm"], g: "food" },

  // ═══ ACTIONS (expand to ~140+) ═══
  "ambush_attack": { c: ["ambush","attack","forest","hide","hunt","shadow","strike","surprise","trap","war"], g: "actions" },
  "beckon": { c: ["call","come","finger","gesture","hand","invite","summon","wave"], g: "actions" },
  "bellow": { c: ["cry","deep","loud","mouth","roar","scream","shout","voice","war"], g: "actions" },
  "betray": { c: ["back","dark","knife","lie","shadow","snake","stab","trust","turn"], g: "actions" },
  "bewitch": { c: ["charm","curse","enchant","eye","magic","moon","spell","witch"], g: "actions" },
  "brandish": { c: ["blade","flash","hand","raise","steel","swing","sword","wave","weapon"], g: "actions" },
  "brew": { c: ["ale","boil","cauldron","drink","heat","herb","mix","pot","tea","water","witch"], g: "actions" },
  "burrow": { c: ["dark","deep","dig","earth","hide","hole","mole","rabbit","tunnel"], g: "actions" },
  "cleave": { c: ["axe","blade","break","cut","divide","split","steel","strike","sword","wood"], g: "actions" },
  "conjure": { c: ["create","fire","ghost","illusion","magic","spell","spirit","summon","wizard"], g: "actions" },
  "cower": { c: ["cold","corner","crouch","dark","fear","hide","kneel","small","tremble"], g: "actions" },
  "creep": { c: ["cold","crawl","dark","foot","hide","night","quiet","shadow","slow","snake","spider"], g: "actions" },
  "crumble_fall": { c: ["ash","break","castle","crumble","crush","dust","fall","ruin","stone","wall","weak"], g: "actions" },
  "dangle": { c: ["chain","hang","rope","spider","string","swing","thread","web"], g: "actions" },
  "dismantle": { c: ["apart","break","build","gear","piece","pull","ruin","stone","take","tool","wall"], g: "actions" },
  "enchant": { c: ["beauty","bewitch","charm","fairy","glow","magic","ring","song","spell","voice","wizard"], g: "actions" },
  "endure": { c: ["brave","cold","fire","hard","iron","long","mountain","pain","stand","stone","storm","strong","time","wall"], g: "actions" },
  "engulf": { c: ["burn","consume","dark","devour","fire","flame","flood","ocean","shadow","swallow","wave"], g: "actions" },
  "entreat": { c: ["ask","beg","cry","hand","hope","kneel","mercy","plea","pray","voice"], g: "actions" },
  "erode_wear": { c: ["cliff","erode","rain","river","rock","sand","slow","stone","time","water","wave","weather","wind"], g: "actions" },
  "erupt": { c: ["ash","blast","burst","explode","fire","hot","lava","magma","red","smoke","volcano"], g: "actions" },
  "excavate": { c: ["bone","deep","dig","earth","fossil","mine","rock","ruin","sand","stone","treasure"], g: "actions" },
  "feast_eat": { c: ["ale","bread","cheese","drink","eat","feast","food","king","meat","mead","table","tavern","wine"], g: "actions" },
  "fetch": { c: ["bring","carry","come","dog","fast","find","get","run","take","throw"], g: "actions" },
  "flicker": { c: ["candle","dim","fire","flame","glow","light","shadow","small","weak","wind"], g: "actions" },
  "forage": { c: ["berry","bush","eat","find","food","forest","gather","herb","mushroom","nut","search","wild"], g: "actions" },
  "fortify": { c: ["brick","build","castle","defend","fortress","guard","iron","moat","stone","strong","tower","wall","war"], g: "actions" },
  "fracture": { c: ["bone","break","crack","glass","ice","rock","shatter","split","stone","weak"], g: "actions" },
  "fray": { c: ["battle","clash","edge","fight","rope","string","tear","thread","war","worn"], g: "actions" },
  "gallop_run": { c: ["dash","fast","gallop","horse","race","ride","run","stallion","swift","wild","wind"], g: "actions" },
  "gleam": { c: ["blade","bright","eye","gem","glow","gold","light","metal","moon","polish","silver","star","steel","sun"], g: "actions" },
  "gnaw": { c: ["bite","bone","eat","hunger","rat","rodent","teeth","wood","worm"], g: "actions" },
  "grapple": { c: ["arm","chain","climb","fight","grip","hand","hold","pull","rope","struggle","wrestle"], g: "actions" },
  "grovel": { c: ["beg","crawl","dust","earth","fear","floor","humble","kneel","low","plea","shame"], g: "actions" },
  "grumble": { c: ["anger","deep","growl","low","mouth","rumble","storm","thunder","voice"], g: "actions" },
  "harness": { c: ["bind","chain","control","horse","leather","pull","ride","rope","strap","tame","yoke"], g: "actions" },
  "harvest_grain": { c: ["autumn","barley","corn","cut","farm","field","gather","grain","harvest","reap","scythe","wheat"], g: "actions" },
  "herald": { c: ["announce","banner","call","come","dawn","flag","horn","king","loud","trumpet","voice","war"], g: "actions" },
  "hoist": { c: ["anchor","banner","flag","heavy","lift","mast","pull","raise","rope","sail","ship","strong"], g: "actions" },
  "ignite_fire": { c: ["burn","ember","fire","flame","hot","ignite","kindle","light","match","spark","torch","wood"], g: "actions" },
  "impale": { c: ["blade","blood","lance","pierce","point","sharp","spear","spike","stab","steel","sword","through"], g: "actions" },
  "implore": { c: ["ask","beg","cry","hand","hope","kneel","mercy","plea","pray","tear","voice"], g: "actions" },
  "invoke": { c: ["call","conjure","fire","magic","name","pray","ritual","spirit","summon","voice","wizard"], g: "actions" },
  "kindle_fire": { c: ["burn","coal","ember","fire","flame","glow","heat","hot","kindle","light","spark","warm","wood"], g: "actions" },
  "knead": { c: ["bake","bread","clay","dough","flour","fold","hand","mix","press","shape","soft","wheat"], g: "actions" },
  "lament_cry": { c: ["cry","death","grief","lament","mourn","sad","sorrow","tear","voice","woe"], g: "actions" },
  "lash": { c: ["bind","crack","hit","leather","pain","rope","sharp","sting","strike","tail","whip","wind"], g: "actions" },
  "linger": { c: ["dusk","ghost","haze","last","late","long","memory","mist","shadow","slow","stay","wait"], g: "actions" },
  "lumber": { c: ["axe","big","cut","heavy","log","slow","strong","timber","tree","walk","wood"], g: "actions" },
  "lunge": { c: ["attack","blade","dash","fast","fight","forward","sharp","strike","sword","thrust"], g: "actions" },
  "meditate_mind": { c: ["breath","calm","close","focus","mind","monk","peace","quiet","silence","sit","soul","still","temple","think"], g: "actions" },
  "mend_fix": { c: ["fix","heal","mend","needle","patch","repair","sew","stitch","thread","torn","weave","whole"], g: "actions" },
  "parry": { c: ["blade","block","defend","fight","guard","shield","steel","strike","sword","turn"], g: "actions" },
  "perch_sit": { c: ["bird","branch","eagle","high","owl","rest","sit","stand","tree","watch"], g: "actions" },
  "pilfer": { c: ["coin","dark","gold","hand","hide","night","secret","shadow","sneak","steal","thief","treasure"], g: "actions" },
  "plunder": { c: ["chest","coin","gold","loot","pirate","raid","rob","steal","sword","treasure","war"], g: "actions" },
  "prevail": { c: ["battle","brave","courage","fight","hero","honor","rise","stand","strong","sword","triumph","victory","war","win"], g: "actions" },
  "prowl_hunt": { c: ["cat","dark","hunt","leopard","night","panther","prowl","shadow","silent","stalk","tiger","wolf"], g: "actions" },
  "quench_thirst": { c: ["cool","drink","fire","pour","quench","rain","river","thirst","water","well"], g: "actions" },
  "rally": { c: ["banner","brave","call","charge","courage","drum","fight","flag","gather","horn","roar","stand","trumpet","war"], g: "actions" },
  "rampage": { c: ["break","bull","charge","crush","destroy","fury","rage","roar","run","smash","storm","wild"], g: "actions" },
  "ravage": { c: ["burn","crush","destroy","devour","fire","flame","ruin","storm","tear","war","wild","wolf","wrath"], g: "actions" },
  "recoil": { c: ["back","fear","horror","jump","pull","shock","snake","spring","surprise","turn"], g: "actions" },
  "repel": { c: ["back","block","defend","fight","force","guard","push","resist","shield","strong","wall"], g: "actions" },
  "restore": { c: ["build","clean","fix","heal","light","mend","new","paint","repair","shine","whole"], g: "actions" },
  "rouse": { c: ["call","courage","dawn","drum","fire","horn","loud","rise","spark","stir","wake","war"], g: "actions" },
  "rumble": { c: ["dark","deep","drum","earth","earthquake","growl","loud","low","roll","storm","thunder"], g: "actions" },
  "scavenge": { c: ["crow","dig","eat","find","food","gather","hunt","pick","ruin","search","vulture","wild","worm"], g: "actions" },
  "scorch": { c: ["ash","black","burn","desert","dry","fire","flame","heat","hot","sand","sun"], g: "actions" },
  "shimmer_glow": { c: ["bright","dawn","gem","gleam","glow","gold","light","moon","silk","silver","star","sun","water"], g: "actions" },
  "siege_war": { c: ["army","barricade","castle","catapult","fortress","gate","moat","ram","siege","tower","wall","war"], g: "actions" },
  "smelt": { c: ["copper","fire","forge","furnace","gold","heat","hot","iron","melt","metal","ore","silver","steel"], g: "actions" },
  "smolder": { c: ["ash","burn","coal","dark","ember","fire","glow","heat","hot","red","smoke","slow"], g: "actions" },
  "sow_seed": { c: ["earth","farm","field","grow","hand","plant","seed","soil","sow","spring","wheat"], g: "actions" },
  "sputter": { c: ["candle","cough","die","drip","fire","flame","rain","spark","water","weak","wind"], g: "actions" },
  "stagger": { c: ["dizzy","drink","fall","heavy","hit","leg","slow","stumble","walk","weak","wound"], g: "actions" },
  "stalk_hunt": { c: ["cat","dark","follow","grass","hunt","leopard","prey","prowl","quiet","shadow","silent","stalk","tiger","wolf"], g: "actions" },
  "stoke": { c: ["bellows","burn","coal","ember","fire","flame","forge","fuel","heat","hot","iron","stir","wood"], g: "actions" },
  "submerge": { c: ["dark","deep","dive","drown","flood","ocean","plunge","sink","swim","tide","under","water","wave"], g: "actions" },
  "surge_wave": { c: ["charge","crash","flood","force","ocean","power","rise","rush","sea","storm","strong","surge","tide","water","wave"], g: "actions" },
  "survey": { c: ["climb","compass","explore","eye","high","horizon","land","look","map","mountain","see","tower","view","watch"], g: "actions" },
  "sway": { c: ["bamboo","breeze","dance","flow","gentle","grass","lean","reed","rhythm","slow","swing","tree","wave","wind","willow"], g: "actions" },
  "thresh": { c: ["barley","beat","farm","flail","grain","harvest","separate","wheat","winnow"], g: "actions" },
  "topple_fall": { c: ["castle","crash","crown","fall","king","ruin","stone","throne","topple","tower","tumble","wall"], g: "actions" },
  "trek": { c: ["boot","climb","far","foot","hill","journey","long","mountain","path","road","trail","walk","wander"], g: "actions" },
  "trudge": { c: ["cold","foot","heavy","long","march","mud","rain","slow","snow","step","tired","walk","wet"], g: "actions" },
  "unearth": { c: ["bone","deep","dig","discover","earth","find","fossil","gold","ground","root","secret","stone","treasure"], g: "actions" },
  "unleash": { c: ["break","chain","dog","fire","force","free","fury","loose","power","rage","release","storm","wild","wind","wolf","wrath"], g: "actions" },
  "unravel_thread": { c: ["code","end","knot","loose","mystery","pull","riddle","rope","secret","solve","thread","unravel","weave"], g: "actions" },
  "usurp": { c: ["betray","crown","dark","king","power","seize","shadow","steal","throne","war"], g: "actions" },
  "vanquish": { c: ["battle","blade","brave","conquer","defeat","dragon","fight","hero","knight","strike","sword","triumph","war","warrior","win"], g: "actions" },
  "vex": { c: ["anger","bother","frustrate","itch","puzzle","riddle","sting","thorn","trouble"], g: "actions" },
  "wade": { c: ["cross","deep","foot","knee","marsh","mud","river","shallow","slow","swamp","walk","water","wet"], g: "actions" },
  "wail": { c: ["cry","dark","ghost","grief","howl","loud","mourn","night","scream","sorrow","voice","wind","woe"], g: "actions" },
  "wield": { c: ["arm","axe","blade","fight","grip","hand","hold","mace","power","staff","steel","strong","sword","weapon"], g: "actions" },
  "winnow": { c: ["air","barley","blow","chaff","farm","grain","separate","thresh","wheat","wind"], g: "actions" },
  "wrangle": { c: ["argue","bull","catch","fight","grip","hold","horse","lasso","pull","rope","struggle","tame","wrestle"], g: "actions" },

  // ═══ BODY (expand to ~100+) ═══
  "abdomen": { c: ["belly","body","gut","hip","muscle","rib","torso","waist"], g: "body" },
  "achilles": { c: ["ankle","foot","heel","leg","run","tendon","weak"], g: "body" },
  "bicep": { c: ["arm","curl","flex","lift","muscle","shoulder","strong"], g: "body" },
  "bladder": { c: ["belly","body","gut","kidney","water"], g: "body" },
  "calf": { c: ["cow","foot","knee","leg","muscle","run","shin"], g: "body" },
  "collarbone": { c: ["bone","chest","neck","shoulder","thin"], g: "body" },
  "cornea": { c: ["eye","iris","lens","light","see","vision"], g: "body" },
  "diaphragm": { c: ["belly","body","breath","chest","lung","rib"], g: "body" },
  "earlobe": { c: ["ear","hang","ring","small","soft"], g: "body" },
  "eyelid": { c: ["blink","close","eye","lash","open","sleep"], g: "body" },
  "femur": { c: ["big","bone","hip","knee","leg","long","strong","thigh"], g: "body" },
  "forearm": { c: ["arm","elbow","grip","hand","muscle","strong","wrist"], g: "body" },
  "gland": { c: ["blood","body","neck","small","sweat","throat"], g: "body" },
  "hamstring": { c: ["knee","leg","muscle","pull","run","thigh"], g: "body" },
  "iris_eye": { c: ["blue","color","eye","green","iris","light","see"], g: "body" },
  "jawbone": { c: ["bite","bone","chin","face","jaw","mouth","teeth"], g: "body" },
  "jugular": { c: ["blood","neck","pulse","throat","vein"], g: "body" },
  "kidney": { c: ["bladder","blood","body","filter","organ","water"], g: "body" },
  "knuckle_fist": { c: ["bone","crack","fight","finger","fist","hand","hit","knuckle","punch"], g: "body" },
  "larynx": { c: ["neck","sing","sound","speak","throat","voice"], g: "body" },
  "ligament": { c: ["bone","joint","knee","pull","stretch","strong","tear","tendon"], g: "body" },
  "lobe": { c: ["brain","ear","lung","round","soft"], g: "body" },
  "molar": { c: ["bite","chew","eat","hard","jaw","mouth","tooth"], g: "body" },
  "nape": { c: ["back","hair","head","kiss","neck","soft"], g: "body" },
  "nostril": { c: ["air","breath","nose","smell"], g: "body" },
  "palm_hand": { c: ["cup","finger","flat","fortune","grab","grip","hand","hold","line","open","palm","read","warm"], g: "body" },
  "pelvis": { c: ["bone","hip","leg","spine","waist"], g: "body" },
  "pupil": { c: ["black","dark","eye","iris","light","round","see","small"], g: "body" },
  "retina": { c: ["eye","iris","lens","light","see","vision"], g: "body" },
  "shin_bone": { c: ["bone","calf","kick","knee","leg","run","shin"], g: "body" },
  "sinew": { c: ["bone","meat","muscle","pull","strong","tendon","tough"], g: "body" },
  "sternum": { c: ["bone","chest","heart","rib","shield","torso"], g: "body" },
  "temple_head": { c: ["brain","head","pulse","side","skin","skull","thin"], g: "body" },
  "tendon_body": { c: ["ankle","bone","hand","joint","knee","muscle","pull","stretch","strong","tendon","wrist"], g: "body" },
  "thorax": { c: ["body","chest","heart","lung","rib","torso"], g: "body" },
  "thyroid": { c: ["body","gland","metabolism","neck","throat"], g: "body" },
  "tibia": { c: ["bone","knee","leg","long","shin","walk"], g: "body" },
  "tricep": { c: ["arm","elbow","lift","muscle","push","shoulder","strong"], g: "body" },
  "ulna": { c: ["arm","bone","elbow","forearm","wrist"], g: "body" },
  "uvula": { c: ["hang","mouth","red","small","throat"], g: "body" },
  "vertebra": { c: ["back","bone","curve","neck","skeleton","spine"], g: "body" },

  // ═══ PLACES (expand to ~100+) ═══
  "alcove": { c: ["arch","corner","dark","hide","nook","shade","shelter","small","wall"], g: "places" },
  "amphitheater": { c: ["arena","circle","colosseum","crowd","music","play","round","sing","stage","stone"], g: "places" },
  "apothecary": { c: ["bottle","cure","heal","herb","medicine","mix","potion","remedy","shop","spice"], g: "places" },
  "aqueduct": { c: ["arch","bridge","carry","flow","Roman","stone","water"], g: "places" },
  "archipelago": { c: ["island","ocean","reef","sail","sea","shore","water","wave"], g: "places" },
  "armory": { c: ["armor","axe","blade","castle","shield","sword","war","weapon"], g: "places" },
  "bakehouse": { c: ["baker","bread","fire","flour","hot","oven","warm","wheat","yeast"], g: "places" },
  "barracks": { c: ["army","bed","guard","knight","soldier","sword","war","warrior"], g: "places" },
  "bastion": { c: ["brick","castle","defend","fortress","gate","guard","stone","tower","wall","war"], g: "places" },
  "bazaar_market": { c: ["bazaar","buy","cloth","coin","crowd","gold","market","merchant","sell","silk","spice","trade"], g: "places" },
  "belfry": { c: ["bell","church","high","ring","rope","sound","stone","tower"], g: "places" },
  "bivouac": { c: ["camp","cold","fire","forest","night","rest","sleep","soldier","tent","wild"], g: "places" },
  "bog_swamp": { c: ["bog","cold","dark","fog","frog","marsh","mist","moss","mud","peat","swamp","water","wet"], g: "places" },
  "burrow_den": { c: ["badger","burrow","dark","den","dig","earth","fox","hole","rabbit","small","tunnel","warm"], g: "places" },
  "cairn": { c: ["climb","hill","mark","mountain","rock","stack","stone","trail"], g: "places" },
  "campfire": { c: ["burn","camp","cook","ember","flame","hot","light","night","smoke","star","warm","wood"], g: "places" },
  "catacomb": { c: ["bone","dark","death","deep","dust","grave","skull","stone","tomb","underground"], g: "places" },
  "causeway": { c: ["bridge","cross","island","ocean","path","road","sea","stone","walk","water"], g: "places" },
  "citadel_fort": { c: ["castle","citadel","defend","fortress","gate","guard","high","king","stone","tower","wall","war"], g: "places" },
  "colosseum_arena": { c: ["arena","battle","colosseum","crowd","fight","gladiator","lion","roar","sand","stone","sword","war"], g: "places" },
  "crypt": { c: ["bone","cold","dark","death","deep","dust","ghost","grave","key","skull","stone","tomb","underground"], g: "places" },
  "den_cave": { c: ["bear","cave","cold","dark","den","fox","hide","sleep","warm","wolf"], g: "places" },
  "drawbridge": { c: ["bridge","castle","chain","cross","gate","iron","moat","open","shut","tower","water"], g: "places" },
  "encampment": { c: ["army","camp","fire","night","soldier","sword","tent","war","warrior"], g: "places" },
  "foundry": { c: ["bronze","copper","fire","forge","furnace","gold","hot","iron","melt","metal","pour","steel"], g: "places" },
  "garrison_fort": { c: ["army","castle","defend","fortress","garrison","gate","guard","knight","soldier","stone","wall","war","warrior"], g: "places" },
  "grotto": { c: ["cave","cool","crystal","dark","deep","drip","moss","pool","rock","spring","stone","water"], g: "places" },
  "harbor_port": { c: ["anchor","boat","coast","dock","fish","harbor","lighthouse","ocean","port","rope","sail","sailor","ship","tide","water","wave","wharf"], g: "places" },
  "hearth_home": { c: ["ash","burn","coal","ember","family","fire","flame","glow","hearth","home","iron","pot","smoke","warm","winter","wood"], g: "places" },
  "hermitage": { c: ["alone","calm","forest","monastery","monk","mountain","peace","pray","quiet","silence","solitude","temple"], g: "places" },
  "hinterland": { c: ["far","field","forest","hill","land","mountain","remote","village","wild"], g: "places" },
  "homestead": { c: ["barn","build","farm","field","home","house","land","plow","well","wood"], g: "places" },
  "infirmary": { c: ["bed","blood","cure","doctor","heal","herb","medicine","pain","rest","wound"], g: "places" },
  "keep_castle": { c: ["castle","defend","dungeon","fort","guard","high","keep","king","knight","stone","tower","wall","war"], g: "places" },
  "lookout": { c: ["climb","eye","far","guard","high","horizon","mountain","see","stand","tower","view","watch"], g: "places" },
  "mesa_flat": { c: ["canyon","desert","flat","high","mesa","plain","plateau","rock","sand","stone","wide"], g: "places" },
  "mineshaft": { c: ["coal","dark","deep","dig","earth","gold","iron","mine","miner","ore","rock","stone","tunnel"], g: "places" },
  "outpost": { c: ["border","camp","castle","defend","far","fort","frontier","guard","soldier","tower","wall","watch"], g: "places" },
  "parapet": { c: ["arrow","castle","defend","guard","high","stone","tower","view","wall","war","watch"], g: "places" },
  "quarry_stone": { c: ["block","cut","deep","dig","dust","granite","marble","mine","pick","quarry","rock","stone"], g: "places" },
  "rampart_wall": { c: ["brick","castle","defend","fort","gate","guard","high","rampart","siege","stone","tower","wall","war"], g: "places" },
  "rookery": { c: ["bird","cliff","colony","crow","egg","nest","noise","raven","rock","sea"], g: "places" },
  "savanna_plain": { c: ["elephant","giraffe","grass","heat","lion","plain","run","savanna","sun","tree","warm","wide","wild","zebra"], g: "places" },
  "shipyard": { c: ["anchor","boat","build","hammer","mast","nail","plank","rope","sail","ship","wood"], g: "places" },
  "smithy": { c: ["anvil","blacksmith","fire","forge","hammer","hot","iron","ring","smith","spark","steel","tool"], g: "places" },
  "stockade": { c: ["defend","fence","fort","gate","guard","log","prison","sharp","stake","wall","wood"], g: "places" },
  "tavern_inn": { c: ["ale","drink","feast","fire","food","inn","mead","mug","music","night","song","tavern","warm","wine"], g: "places" },
  "thatched": { c: ["hay","house","old","roof","straw","thatch","village","warm","wood"], g: "places" },
  "turret": { c: ["archer","arrow","castle","defend","guard","high","round","stone","tower","view","wall","watch"], g: "places" },
  "vineyard_farm": { c: ["autumn","fruit","grape","grow","harvest","leaf","sun","vine","vineyard","wine"], g: "places" },
  "watchtower": { c: ["beacon","border","castle","fire","guard","high","light","night","see","stand","stone","tower","view","wall","watch"], g: "places" },

  // ═══ COLORS (expand to ~45+) ═══
  "amber_gold": { c: ["amber","autumn","gem","glow","gold","honey","light","orange","sun","warm","yellow"], g: "colors" },
  "celadon": { c: ["clay","cool","gentle","glaze","green","jade","light","pale","soft","water"], g: "colors" },
  "cerulean": { c: ["azure","blue","calm","clear","cloud","ocean","sky","water"], g: "colors" },
  "chartreuse": { c: ["bright","green","leaf","light","lime","spring","yellow"], g: "colors" },
  "cobalt_blue": { c: ["blue","cobalt","dark","deep","gem","metal","ocean","paint","sea","strong"], g: "colors" },
  "copper_color": { c: ["autumn","brown","copper","earth","metal","orange","penny","red","rust","warm"], g: "colors" },
  "coral_color": { c: ["coral","ocean","orange","peach","pink","reef","sea","soft","warm","water"], g: "colors" },
  "cream_color": { c: ["butter","cream","ivory","light","milk","pale","silk","smooth","soft","warm","white"], g: "colors" },
  "dusk_color": { c: ["dark","dim","dusk","gray","night","orange","purple","red","shadow","sunset","twilight","violet"], g: "colors" },
  "flax": { c: ["cloth","field","gold","linen","pale","plant","straw","thread","weave","yellow"], g: "colors" },
  "gilt": { c: ["bright","frame","gleam","glow","gold","leaf","paint","rich","shine","thin"], g: "colors" },
  "indigo_blue": { c: ["blue","dark","deep","dye","night","purple","rich","sky","violet"], g: "colors" },
  "khaki": { c: ["brown","desert","dry","dust","earth","sand","tan","warm","yellow"], g: "colors" },
  "lilac": { c: ["bloom","flower","fragrance","gentle","light","pale","purple","soft","spring","sweet","violet"], g: "colors" },
  "mahogany": { c: ["brown","dark","deep","furniture","polish","red","rich","smooth","tree","warm","wood"], g: "colors" },
  "mauve": { c: ["dusk","fade","flower","gentle","gray","pale","pink","purple","soft","twilight","violet"], g: "colors" },
  "olive_color": { c: ["brown","dark","earth","green","military","mute","olive","tree","warm","yellow"], g: "colors" },
  "pearl_white": { c: ["cream","glow","ivory","light","moon","oyster","pale","pearl","shimmer","silver","smooth","soft","water","white"], g: "colors" },
  "pewter": { c: ["cold","cup","dull","goblet","gray","lead","metal","mug","silver","tin"], g: "colors" },
  "rust_color": { c: ["autumn","brown","dark","decay","earth","iron","old","orange","red","rust","warm"], g: "colors" },
  "sage_green": { c: ["calm","cool","dust","garden","gentle","gray","green","herb","mute","pale","sage","soft"], g: "colors" },
  "sable": { c: ["black","coat","dark","fur","night","rich","shadow","smooth","soft"], g: "colors" },
  "sienna": { c: ["brown","clay","earth","orange","paint","red","rust","warm"], g: "colors" },
  "slate_gray": { c: ["cold","cool","dark","gray","heavy","rain","rock","roof","slate","stone","wet"], g: "colors" },
  "tan": { c: ["beach","brown","dust","earth","leather","light","pale","sand","skin","sun","warm"], g: "colors" },
  "umber": { c: ["brown","dark","dust","earth","mud","paint","rich","soil","warm"], g: "colors" },

  // ═══ PROFESSIONS (expand to ~75+) ═══
  "alchemist_old": { c: ["alchemist","book","fire","flask","gold","magic","mercury","old","philosopher","potion","wizard"], g: "professions" },
  "apothecary_herb": { c: ["bottle","cure","heal","herb","mix","mortar","plant","potion","remedy","root","spice"], g: "professions" },
  "bowyer": { c: ["arrow","bend","bow","craft","string","weapon","wood","yew"], g: "professions" },
  "cobbler": { c: ["boot","craft","foot","hammer","leather","nail","needle","shoe","sole","stitch","thread","walk"], g: "professions" },
  "cooper": { c: ["barrel","bend","bucket","craft","oak","ring","stave","tub","wood"], g: "professions" },
  "courier": { c: ["deliver","fast","horse","letter","message","ride","road","run","scroll","swift"], g: "professions" },
  "druid": { c: ["earth","forest","green","heal","herb","magic","moon","nature","oak","plant","sacred","stone","tree","wild"], g: "professions" },
  "dyer": { c: ["blue","cloth","color","dye","fabric","indigo","purple","red","silk","stain","wool"], g: "professions" },
  "falconer": { c: ["bird","falcon","fly","glove","hawk","hunt","sky","train","wing"], g: "professions" },
  "fletcher": { c: ["arrow","craft","feather","flint","sharp","straight","wood"], g: "professions" },
  "glassblower": { c: ["blow","fire","flame","glass","hot","melt","round","shape","spin"], g: "professions" },
  "herald_prof": { c: ["announce","banner","call","court","crown","flag","horn","king","loud","news","trumpet"], g: "professions" },
  "herbalist_prof": { c: ["cure","flower","forest","garden","green","grow","heal","herb","herbalist","leaf","plant","remedy","root"], g: "professions" },
  "inquisitor": { c: ["church","dark","eye","fire","judge","law","question","search","truth"], g: "professions" },
  "ironmonger": { c: ["forge","hammer","iron","metal","nail","sell","shop","steel","tool"], g: "professions" },
  "jester": { c: ["bell","cap","color","court","dance","fool","fun","jest","king","laugh","trick"], g: "professions" },
  "locksmith": { c: ["bolt","brass","craft","door","gate","iron","key","lock","metal","open","pick","tool"], g: "professions" },
  "midwife": { c: ["baby","birth","child","gentle","hand","heal","help","mother","night","woman","womb"], g: "professions" },
  "miller": { c: ["flour","grain","grind","mill","stone","water","wheat","wheel","wind"], g: "professions" },
  "minstrel": { c: ["dance","fiddle","lute","melody","music","play","sing","song","string","tale","tavern","voice"], g: "professions" },
  "page_squire": { c: ["armor","boy","castle","court","horse","king","knight","learn","serve","shield","sword","young"], g: "professions" },
  "ranger_forest": { c: ["arrow","bow","deer","forest","green","hunt","path","ranger","scout","track","tree","wild","wood","wolf"], g: "professions" },
  "scribe": { c: ["book","ink","letter","page","paper","pen","quill","read","scroll","write","word"], g: "professions" },
  "sentinel_guard": { c: ["castle","dawn","eye","gate","guard","knight","night","shield","stand","tower","vigil","wall","war","watch"], g: "professions" },
  "sentry": { c: ["border","castle","dawn","gate","guard","knight","night","stand","tower","vigil","wall","watch"], g: "professions" },
  "shepherd_flock": { c: ["dog","field","flock","grass","herd","hill","lamb","mountain","path","sheep","shepherd","staff","walk","wool"], g: "professions" },
  "shipwright": { c: ["anchor","boat","build","craft","hull","mast","nail","oak","plank","rope","sail","ship","tar","wood"], g: "professions" },
  "squire": { c: ["armor","boy","castle","horse","knight","learn","ride","serve","shield","sword","train","young"], g: "professions" },
  "steward": { c: ["castle","coin","count","gold","guard","hall","house","key","king","manage","serve"], g: "professions" },
  "stonecutter": { c: ["block","carve","chisel","dust","granite","hammer","marble","mason","quarry","rock","stone","wall"], g: "professions" },
  "tanner": { c: ["bark","brown","cow","cure","dry","hide","knife","leather","skin","stretch","tan","water"], g: "professions" },
  "thatcher": { c: ["hay","house","reed","roof","straw","thatch","village","warm","weave","wood"], g: "professions" },
  "tinker": { c: ["copper","craft","fix","hammer","kettle","mend","metal","pot","repair","road","tin","tool","travel","wander"], g: "professions" },
  "wheelwright": { c: ["axle","build","cart","craft","hub","iron","oak","rim","round","spoke","wagon","wheel","wood"], g: "professions" },

  // ═══ WEATHER (expand to ~40+) ═══
  "blizzard_snow": { c: ["blizzard","blind","cold","freeze","howl","ice","snow","storm","white","wild","wind","winter"], g: "weather" },
  "chinook": { c: ["dry","hot","melt","mountain","snow","thaw","warm","west","wind"], g: "weather" },
  "drizzle": { c: ["cold","damp","fog","gentle","gray","light","mist","rain","sky","soft","wet"], g: "weather" },
  "flurry": { c: ["blow","cold","flutter","ice","light","quick","snow","spin","swirl","white","wind","winter"], g: "weather" },
  "frost_ice": { c: ["bite","cold","crystal","freeze","frost","glass","ice","morning","pattern","silver","white","window","winter"], g: "weather" },
  "hailstorm": { c: ["cold","crash","damage","hail","hard","hit","ice","loud","rain","stone","storm","white"], g: "weather" },
  "heat_wave": { c: ["burn","desert","dry","dust","fire","gold","heat","hot","red","sand","shimmer","sun","summer","sweat","warm"], g: "weather" },
  "mist_fog": { c: ["blur","breath","cold","damp","dawn","dim","fog","ghost","gray","haze","hide","mist","morning","pale","rain","shadow","soft","water","wet","white"], g: "weather" },
  "nor_easter": { c: ["blow","cold","coast","gale","ocean","rain","sea","storm","strong","wave","wet","wind","winter"], g: "weather" },
  "permafrost": { c: ["cold","deep","earth","freeze","frozen","hard","ice","soil","tundra","winter"], g: "weather" },
  "rainbow_arc": { c: ["arc","arch","color","gold","joy","light","rain","rainbow","red","sky","storm","sun","violet","water","yellow"], g: "weather" },
  "sirocco": { c: ["burn","desert","dry","dust","hot","sand","south","summer","warm","wind"], g: "weather" },
  "sleet_ice": { c: ["cold","fall","freeze","gray","ice","rain","sharp","sleet","slippery","snow","sting","water","wet","winter"], g: "weather" },
  "squall_wind": { c: ["blow","cloud","cold","gust","ocean","rain","sharp","squall","storm","sudden","water","wave","wet","wind"], g: "weather" },
  "thaw_spring": { c: ["drip","flow","ice","melt","mud","river","snow","soft","spring","stream","sun","thaw","warm","water","wet"], g: "weather" },
  "whirlwind": { c: ["blow","circle","dust","fast","gust","sand","spin","storm","swirl","tornado","turn","wild","wind"], g: "weather" },
  "zephyr": { c: ["blow","breeze","calm","cool","flower","gentle","grass","green","light","soft","spring","sweet","warm","west","wind"], g: "weather" },

  // ═══ MYTHOLOGY (expand to ~45+) ═══
  "banshee": { c: ["cry","dark","death","ghost","howl","irish","mourn","night","scream","spirit","wail","wind"], g: "mythology" },
  "basilisk": { c: ["death","eye","gaze","kill","lizard","poison","serpent","snake","stone","venom"], g: "mythology" },
  "cerberus": { c: ["dark","death","dog","gate","guard","hound","monster","three","underworld"], g: "mythology" },
  "changeling": { c: ["baby","child","fairy","forest","magic","replace","steal","trick","wild"], g: "mythology" },
  "djinn": { c: ["bottle","desert","fire","lamp","magic","sand","smoke","spirit","summon","wish"], g: "mythology" },
  "dryad": { c: ["dance","forest","green","leaf","nature","oak","spirit","tree","wild","wood"], g: "mythology" },
  "fenrir": { c: ["bite","chain","dark","fang","giant","god","howl","ice","wolf"], g: "mythology" },
  "gorgon": { c: ["eye","gaze","monster","serpent","snake","stone","turn","venom","woman"], g: "mythology" },
  "harpy": { c: ["bird","claw","cry","feather","fly","monster","scream","steal","storm","wing","woman"], g: "mythology" },
  "imp": { c: ["dark","devil","fire","magic","mischief","prank","small","trick"], g: "mythology" },
  "kelpie": { c: ["dark","drown","green","horse","lake","lure","spirit","water","wild"], g: "mythology" },
  "leviathan": { c: ["abyss","dark","deep","giant","kraken","monster","ocean","sea","serpent","whale","water","wave"], g: "mythology" },
  "manticore": { c: ["claw","fang","fly","hunt","lion","monster","poison","scorpion","spike","tail","venom","wing"], g: "mythology" },
  "nymph": { c: ["beauty","dance","forest","grace","green","lake","nature","river","spirit","stream","tree","water","wild"], g: "mythology" },
  "odin": { c: ["crow","eye","god","norse","raven","rune","spear","war","wisdom","wolf"], g: "mythology" },
  "selkie": { c: ["coat","cold","fur","ice","ocean","seal","sea","shore","sing","spirit","swim","water","wave"], g: "mythology" },
  "sprite": { c: ["dance","fairy","fast","flower","forest","glow","green","light","magic","small","sparkle","spring","water","wing"], g: "mythology" },
  "thunderbird": { c: ["bird","cloud","eagle","fly","giant","lightning","rain","sky","storm","thunder","wing"], g: "mythology" },
  "trickster": { c: ["clever","crow","cunning","dark","fox","jest","joke","magic","prank","riddle","trick","wolf"], g: "mythology" },
  "valkyrie": { c: ["battle","brave","death","fly","horse","honor","knight","norse","ride","shield","sky","sword","war","warrior","wing","woman"], g: "mythology" },
  "wendigo": { c: ["bone","cold","dark","death","forest","frost","hunger","ice","monster","night","skeleton","snow","spirit","winter"], g: "mythology" },
  "wyvern": { c: ["claw","dragon","fang","fire","fly","monster","scale","tail","venom","wing"], g: "mythology" },

  // ═══ MUSIC (expand to ~55+) ═══
  "aria": { c: ["high","melody","opera","sing","solo","soprano","voice"], g: "music" },
  "ballad": { c: ["cry","love","melody","sad","sing","slow","song","story","tale","voice"], g: "music" },
  "barcarolle": { c: ["boat","gondola","melody","oar","row","sing","slow","song","water","wave"], g: "music" },
  "cadence": { c: ["beat","drum","end","fall","march","pulse","rhythm","step","tempo"], g: "music" },
  "canticle": { c: ["angel","choir","church","holy","hymn","praise","sacred","sing","soul","voice"], g: "music" },
  "cantata": { c: ["choir","church","compose","hymn","orchestra","sacred","sing","solo","voice"], g: "music" },
  "chant": { c: ["deep","low","monk","pray","repeat","rhythm","sacred","sing","slow","temple","voice"], g: "music" },
  "concerto": { c: ["compose","fast","orchestra","piano","play","slow","solo","violin"], g: "music" },
  "crescendo": { c: ["build","climb","drum","forte","grow","high","loud","music","peak","power","rise","swell","wave"], g: "music" },
  "dirge": { c: ["dark","death","drum","grief","low","mourn","sad","slow","song","sorrow"], g: "music" },
  "encore": { c: ["again","applaud","cheer","end","joy","more","play","repeat","sing","stage"], g: "music" },
  "fanfare": { c: ["announce","brass","bright","drum","horn","king","loud","march","trumpet"], g: "music" },
  "fugue": { c: ["bach","chase","compose","layer","melody","pattern","repeat","run","voice","weave"], g: "music" },
  "gigue": { c: ["dance","fast","fiddle","hop","joy","jump","lively","quick","spin","step"], g: "music" },
  "harmony_music": { c: ["balance","blend","chord","harmony","melody","peace","rich","sing","smooth","song","sweet","tune","voice"], g: "music" },
  "interlude": { c: ["between","bridge","calm","dream","light","middle","music","pause","quiet","rest","soft"], g: "music" },
  "lament_song": { c: ["cry","dark","death","grief","lament","low","mourn","sad","slow","song","sorrow","tear","voice","woe"], g: "music" },
  "lilt": { c: ["bounce","bright","dance","gentle","light","melody","rhythm","sing","soft","sweet","swing","voice"], g: "music" },
  "lyre": { c: ["ancient","god","gold","greek","harp","melody","muse","play","pluck","sing","song","string"], g: "music" },
  "madrigal": { c: ["choir","harmony","love","melody","old","sing","song","sweet","voice"], g: "music" },
  "minuet": { c: ["bow","court","dance","elegant","gentle","graceful","music","slow","step","waltz"], g: "music" },
  "nocturne": { c: ["calm","dark","dream","gentle","moon","night","piano","quiet","sleep","slow","soft","star"], g: "music" },
  "opus": { c: ["compose","create","great","masterpiece","music","number","orchestrate","work","write"], g: "music" },
  "prelude": { c: ["begin","calm","dawn","first","gentle","introduce","open","piano","quiet","soft","start"], g: "music" },
  "refrain": { c: ["again","chorus","melody","repeat","return","rhythm","round","sing","song","voice"], g: "music" },
  "rhapsody": { c: ["bold","bright","dance","emotion","free","joy","melody","music","passion","piano","wild"], g: "music" },
  "rondo": { c: ["circle","dance","fast","joy","loop","melody","music","repeat","return","round","spin"], g: "music" },
  "shanty": { c: ["boat","crew","ocean","pull","rope","row","sail","sailor","sea","ship","sing","song","wave"], g: "music" },
  "staccato": { c: ["beat","bounce","crisp","drum","fast","note","quick","rhythm","sharp","short","tap","tempo"], g: "music" },
  "toccata": { c: ["bright","fast","finger","keyboard","organ","piano","play","quick","run","sharp","virtuoso"], g: "music" },
  "vibrato": { c: ["cello","quiver","rich","shake","sing","string","tremble","violin","voice","warm","wave"], g: "music" },

  // ═══ MATERIALS (expand to ~55+) ═══
  "ash_wood": { c: ["ash","bark","bow","craft","grain","handle","hard","strong","tree","white","wood"], g: "materials" },
  "balsa": { c: ["craft","float","light","model","raft","soft","thin","tree","water","wood"], g: "materials" },
  "birch_wood": { c: ["bark","birch","craft","light","paper","pale","smooth","tree","white","wood"], g: "materials" },
  "calfskin": { c: ["bind","book","cow","drum","leather","smooth","soft","thin","write"], g: "materials" },
  "canvas_cloth": { c: ["canvas","cloth","cotton","paint","painter","rough","sail","stretch","tent","thick","white"], g: "materials" },
  "cedar_wood": { c: ["aromatic","cedar","chest","craft","red","resist","rot","smell","tree","warm","wood"], g: "materials" },
  "chalk": { c: ["cliff","draw","dust","mark","soft","stone","white","write"], g: "materials" },
  "charcoal_draw": { c: ["ash","black","burn","charcoal","dark","draw","fire","mark","smoke","soft","wood","write"], g: "materials" },
  "clay_earth": { c: ["brown","clay","craft","dig","earth","form","mold","mud","pot","potter","shape","smooth","soft","water","wet"], g: "materials" },
  "cobalt_metal": { c: ["blue","cobalt","hard","metal","mine","ore","paint","strong"], g: "materials" },
  "cork": { c: ["bark","bottle","brown","float","light","oak","seal","soft","tree","wine","wood"], g: "materials" },
  "ebony_wood": { c: ["black","carve","dark","dense","ebony","hard","heavy","piano","polish","rich","smooth","tree","wood"], g: "materials" },
  "fleece": { c: ["coat","fluffy","lamb","sheep","shear","soft","warm","white","winter","wool"], g: "materials" },
  "flint_stone": { c: ["chip","edge","fire","flint","hard","knife","sharp","spark","stone","strike","tool"], g: "materials" },
  "graphite": { c: ["black","carbon","dark","draw","gray","lead","mark","pencil","smooth","soft","write"], g: "materials" },
  "horsehair": { c: ["bow","brush","horse","mane","string","tail","violin","weave"], g: "materials" },
  "jute": { c: ["brown","cloth","coarse","fiber","rope","rough","sack","string","weave"], g: "materials" },
  "limestone": { c: ["build","cliff","fossil","gray","hard","pale","quarry","rock","shell","soft","stone","wall","white"], g: "materials" },
  "lye": { c: ["ash","burn","clean","harsh","soap","strong","wash","water","white","wood"], g: "materials" },
  "mahogany_wood": { c: ["brown","carve","dark","deep","furniture","hard","mahogany","polish","red","rich","smooth","strong","tree","warm","wood"], g: "materials" },
  "mica": { c: ["flake","glitter","layer","mineral","rock","shimmer","silver","sparkle","thin","transparent"], g: "materials" },
  "obsidian_stone": { c: ["black","blade","dark","edge","glass","obsidian","sharp","smooth","stone","volcanic","volcano"], g: "materials" },
  "onyx": { c: ["bead","black","carve","dark","gem","glossy","hard","jewel","polish","ring","smooth","stone"], g: "materials" },
  "papyrus": { c: ["ancient","dry","egypt","ink","old","paper","plant","read","reed","roll","scroll","write"], g: "materials" },
  "pitch": { c: ["black","burn","coat","dark","hot","seal","ship","sticky","tar","thick","torch","waterproof","wood"], g: "materials" },
  "rawhide": { c: ["bind","cow","drum","hard","leather","raw","rope","skin","stretch","strong","tough","wrap"], g: "materials" },
  "resin": { c: ["amber","coat","glue","hard","pine","seal","shiny","sticky","tree","varnish","wood","yellow"], g: "materials" },
  "sandstone": { c: ["brown","canyon","carve","cliff","desert","dry","orange","red","rock","sand","soft","stone","warm","yellow"], g: "materials" },
  "shale": { c: ["cliff","crack","dark","flat","gray","layer","rock","slate","stone","thin"], g: "materials" },
  "sinew_cord": { c: ["bind","bow","cord","dry","hard","muscle","pull","sinew","stretch","string","strong","tough"], g: "materials" },
  "slate_stone": { c: ["board","cold","dark","flat","gray","heavy","roof","rock","sharp","slate","smooth","stone","thin","write"], g: "materials" },
  "soapstone": { c: ["carve","gray","green","heavy","polish","pot","smooth","soft","stone","warm"], g: "materials" },
  "teak": { c: ["boat","brown","craft","deck","hard","oil","resist","ship","strong","tree","water","wood"], g: "materials" },
  "terracotta": { c: ["brown","clay","earth","fire","flower","hard","kiln","orange","pot","red","tile","warm"], g: "materials" },
  "thatch_straw": { c: ["dry","golden","grass","hay","insulate","reed","roof","straw","thatch","village","warm","weave","yellow"], g: "materials" },
  "tin_metal": { c: ["bright","can","coat","cold","foil","light","metal","mine","plate","rust","shine","silver","thin","tin"], g: "materials" },
  "vellum": { c: ["bind","book","calf","ink","leather","old","parchment","read","scroll","skin","smooth","thin","write"], g: "materials" },
  "walnut_wood": { c: ["brown","carve","craft","dark","furniture","grain","hard","nut","polish","rich","smooth","tree","walnut","wood"], g: "materials" },
  "yew": { c: ["ancient","bow","dark","death","evergreen","graveyard","green","hard","old","poison","red","tree","wood"], g: "materials" },

  // ═══ CELESTIAL (expand to ~60+) ═══
  "aphelion": { c: ["cold","dark","distant","far","orbit","planet","sol","space","sun"], g: "celestial" },
  "asterism": { c: ["bright","constellation","group","night","pattern","sky","star"], g: "celestial" },
  "binary_star": { c: ["dance","glow","light","orbit","pair","spin","star","twin"], g: "celestial" },
  "corona_sun": { c: ["bright","eclipse","fire","glow","gold","halo","hot","light","ring","sun"], g: "celestial" },
  "dwarf_star": { c: ["cold","dim","faint","glow","old","red","small","star"], g: "celestial" },
  "equinox_sky": { c: ["autumn","balance","day","equinox","equal","night","spring","sun"], g: "celestial" },
  "firmament": { c: ["above","blue","cosmos","dome","heaven","high","night","sky","star","universe","vast"], g: "celestial" },
  "galaxy_deep": { c: ["cosmos","dark","deep","galaxy","light","milkyway","nebula","space","spiral","star","universe","vast","void"], g: "celestial" },
  "gibbous": { c: ["bright","crescent","full","glow","half","light","lunar","moon","night","phase","round","shadow","wax"], g: "celestial" },
  "meridian": { c: ["arc","circle","cross","earth","high","line","middle","noon","pass","path","sky","sun","zenith"], g: "celestial" },
  "meteor_sky": { c: ["blaze","bright","burn","fall","fast","fire","flash","fly","light","night","sky","star","streak","swift","trail"], g: "celestial" },
  "nadir": { c: ["below","bottom","dark","deep","down","earth","fall","low","under","void"], g: "celestial" },
  "nebula_cloud": { c: ["cloud","color","cosmos","dark","dust","galaxy","gas","glow","light","nebula","night","space","star","swirl","vast"], g: "celestial" },
  "north_star": { c: ["bright","compass","constant","guide","navigate","night","north","pole","sky","star","steady"], g: "celestial" },
  "perihelion": { c: ["close","fast","hot","near","orbit","planet","sol","space","sun","warm"], g: "celestial" },
  "planetoid": { c: ["cold","dark","orbit","planet","rock","small","space","star","stone"], g: "celestial" },
  "quasar": { c: ["bright","cosmos","distant","energy","far","galaxy","glow","light","power","space","star"], g: "celestial" },
  "red_giant": { c: ["big","burn","glow","hot","huge","light","old","red","star","vast"], g: "celestial" },
  "shooting_star": { c: ["blaze","bright","burn","fall","fast","fire","flash","fly","light","meteor","night","sky","star","streak","swift","trail","wish"], g: "celestial" },
  "solstice_sun": { c: ["cold","dark","day","fire","hot","light","long","short","solstice","summer","sun","warm","winter"], g: "celestial" },
  "sunspot": { c: ["dark","fire","hot","magnetic","patch","spot","sun","surface"], g: "celestial" },
  "twilight_sky": { c: ["blue","calm","dark","dim","dusk","evening","fade","glow","gray","light","moon","night","orange","purple","shadow","sky","soft","star","sunset","twilight"], g: "celestial" },
  "void_space": { c: ["abyss","black","cold","cosmos","dark","deep","empty","galaxy","nothing","silence","space","star","vast","void"], g: "celestial" },
  "waning_moon": { c: ["crescent","dark","dim","fade","half","lunar","moon","night","shadow","shrink","thin"], g: "celestial" },
  "waxing_moon": { c: ["bright","crescent","glow","grow","half","light","lunar","moon","night","phase","rise","wax"], g: "celestial" },

  // ═══ WARFARE (expand to ~35+) ═══
  "ballista": { c: ["bolt","castle","catapult","iron","launch","siege","stone","throw","war","weapon","wood"], g: "warfare" },
  "battering_ram": { c: ["break","castle","charge","crush","door","gate","iron","siege","strong","war","wood"], g: "warfare" },
  "broadsword": { c: ["blade","fight","heavy","iron","knight","slash","steel","strong","swing","sword","war","warrior","weapon"], g: "warfare" },
  "bulwark": { c: ["bastion","brick","castle","defend","fortress","gate","guard","rampart","shield","stone","strong","tower","wall","war"], g: "warfare" },
  "chariot": { c: ["charge","fast","horse","race","ride","roman","speed","war","wheel"], g: "warfare" },
  "claymore": { c: ["battle","blade","fight","heavy","highland","iron","knight","long","steel","strong","swing","sword","two","war","warrior","weapon"], g: "warfare" },
  "crossbow": { c: ["aim","arrow","bolt","bow","hunt","iron","shoot","trigger","war","weapon","wood"], g: "warfare" },
  "flanking": { c: ["army","attack","battle","cavalry","charge","horse","side","strategy","surprise","surround","tactic","war"], g: "warfare" },
  "halberd": { c: ["axe","blade","guard","iron","long","pike","pole","spear","steel","swing","war","weapon"], g: "warfare" },
  "longbow": { c: ["aim","archer","arrow","bow","far","fly","hunt","range","shoot","string","war","weapon","wood","yew"], g: "warfare" },
  "morningstar": { c: ["chain","crush","fight","hit","iron","knight","mace","spike","steel","swing","war","weapon"], g: "warfare" },
  "phalanx": { c: ["army","close","defend","formation","march","row","shield","soldier","spear","strong","wall","war","warrior"], g: "warfare" },
  "portcullis": { c: ["bar","castle","chain","close","defend","gate","grate","guard","heavy","iron","lift","shut","wall","war"], g: "warfare" },
  "rapier": { c: ["blade","duel","fast","fight","light","lunge","parry","pierce","sharp","steel","swift","sword","thin","thrust","weapon"], g: "warfare" },
  "scimitar": { c: ["blade","curve","cut","desert","fight","flash","quick","sand","sharp","slash","steel","swift","sword","war","weapon"], g: "warfare" },
  "trebuchet": { c: ["castle","catapult","crush","hurl","launch","rock","siege","stone","throw","wall","war","weapon","wood"], g: "warfare" },
  "vanguard": { c: ["army","battle","brave","charge","first","front","lead","march","scout","soldier","sword","war","warrior"], g: "warfare" },
  "war_drum": { c: ["army","beat","boom","charge","drum","fear","loud","march","rally","rhythm","soldier","thunder","war"], g: "warfare" },
  "warhammer": { c: ["armor","blow","crush","dwarf","fight","heavy","hit","iron","knight","smash","steel","strong","war","weapon"], g: "warfare" },

  // ═══ ELEMENTS (expand to ~75+) ═══
  "alkali": { c: ["burn","chemical","dissolve","earth","mineral","salt","strong","water","white"], g: "elements" },
  "arsenic": { c: ["dark","death","green","metal","mineral","poison","white"], g: "elements" },
  "basite": { c: ["dark","dense","earth","hard","heavy","iron","lava","magma","rock","volcanic"], g: "elements" },
  "bismuth": { c: ["color","crystal","iridescent","metal","mineral","pink","rainbow","step"], g: "elements" },
  "brimstone": { c: ["burn","demon","fire","hell","hot","smell","sulfur","yellow"], g: "elements" },
  "calcium": { c: ["bone","chalk","hard","milk","mineral","rock","shell","stone","strong","tooth","white"], g: "elements" },
  "chromium": { c: ["bright","hard","metal","mirror","polish","reflect","shine","silver","steel","strong"], g: "elements" },
  "feldspar": { c: ["crystal","earth","hard","mineral","pink","rock","sparkle","stone","white"], g: "elements" },
  "galena": { c: ["crystal","dark","gray","heavy","lead","metal","mine","mineral","ore","silver","stone"], g: "elements" },
  "gneiss": { c: ["band","crystal","earth","fold","granite","hard","layer","old","rock","stone","stripe"], g: "elements" },
  "graphite_ore": { c: ["black","carbon","dark","draw","gray","mark","mine","mineral","pencil","soft","write"], g: "elements" },
  "hematite": { c: ["blood","dark","earth","hard","iron","metal","mineral","ore","red","rock","rust","stone"], g: "elements" },
  "kaolin": { c: ["china","clay","earth","fine","porcelain","pottery","smooth","soft","white"], g: "elements" },
  "magnesium": { c: ["bright","burn","fire","flash","light","metal","mineral","spark","white"], g: "elements" },
  "manganese": { c: ["dark","earth","hard","iron","metal","mineral","ore","purple","steel","strong"], g: "elements" },
  "ore_vein": { c: ["copper","dig","earth","gold","iron","metal","mine","miner","ore","rich","rock","silver","vein"], g: "elements" },
  "phosphorus": { c: ["bone","bright","burn","fire","glow","green","light","match","spark","white"], g: "elements" },
  "potash": { c: ["ash","earth","farm","fertile","grow","mineral","plant","salt","soil","wood"], g: "elements" },
  "pyrite": { c: ["crystal","cube","fool","gem","glitter","gold","iron","metal","mine","mineral","rock","shine","spark","stone","sulfur","yellow"], g: "elements" },
  "saltpeter": { c: ["crystal","earth","fire","gunpowder","mineral","preserve","salt","soil","white"], g: "elements" },
  "selenium": { c: ["glass","metal","mineral","moon","orange","red","selenium"], g: "elements" },
  "silica": { c: ["crystal","dust","earth","fine","glass","hard","mineral","quartz","rock","sand","stone","white"], g: "elements" },
  "slag": { c: ["ash","fire","forge","glass","hot","iron","melt","metal","pour","slag","steel","waste"], g: "elements" },
  "soda_ash": { c: ["alkali","ash","clean","glass","mineral","salt","soap","wash","white"], g: "elements" },
  "talc": { c: ["chalk","dust","flat","mineral","polish","powder","smooth","soft","stone","white"], g: "elements" },
  "zinc": { c: ["coat","cold","galvanize","gray","hard","metal","mineral","ore","protect","rust","steel","white"], g: "elements" }
};

let newCount = 0, enhancedCount = 0, newConns = 0;
for (const [word, data] of Object.entries(newConcepts)) {
  if (!concepts[word]) {
    concepts[word] = { c: data.c.slice(), g: data.g };
    newCount++;
  } else {
    let added = 0;
    for (const conn of data.c) {
      if (!concepts[word].c.includes(conn)) {
        concepts[word].c.push(conn);
        added++;
      }
    }
    if (added > 0) { enhancedCount++; newConns += added; }
  }
}

let bidiFixed = 0;
for (const [word, data] of Object.entries(concepts)) {
  for (const conn of data.c) {
    if (concepts[conn] && !concepts[conn].c.includes(word)) {
      concepts[conn].c.push(word);
      bidiFixed++;
    }
  }
}

let danglingRemoved = 0;
for (const [word, data] of Object.entries(concepts)) {
  const before = data.c.length;
  data.c = data.c.filter(conn => concepts[conn]);
  danglingRemoved += before - data.c.length;
}

const isolated = Object.entries(concepts).filter(([w, d]) => d.c.length === 0).map(([w]) => w);
for (const w of isolated) { delete concepts[w]; }

for (const data of Object.values(concepts)) {
  data.c = [...new Set(data.c)].sort();
}

const lines = [];
const sortedWords = Object.keys(concepts).sort();
for (const w of sortedWords) {
  const d = concepts[w];
  const conns = d.c.map(c => `"${c}"`).join(',');
  lines.push(`    "${w}": { c: [${conns}], g: "${d.g}" }`);
}
const newConceptsStr = '{\n' + lines.join(',\n') + '\n  }';
src = src.substring(0, startIdx) + newConceptsStr + src.substring(endIdx + 1);
fs.writeFileSync('data-core.js', src);

// BFS connectivity
const visited = new Set();
const queue = [sortedWords[0]];
visited.add(sortedWords[0]);
while (queue.length) {
  const w = queue.shift();
  for (const c of concepts[w].c) {
    if (!visited.has(c)) { visited.add(c); queue.push(c); }
  }
}

const groups = {};
for (const [w, d] of Object.entries(concepts)) {
  groups[d.g] = (groups[d.g] || 0) + 1;
}

let totalConns = 0, unidir = 0;
for (const [w, d] of Object.entries(concepts)) {
  for (const c of d.c) { totalConns++; if (concepts[c] && !concepts[c].c.includes(w)) unidir++; }
}

console.log('=== WAVE 2 RESULTS ===');
console.log('New concepts added:', newCount);
console.log('Existing enhanced:', enhancedCount);
console.log('New connections:', newConns);
console.log('Bidirectional fixes:', bidiFixed);
console.log('Dangling removed:', danglingRemoved);
console.log('Isolated removed:', isolated.length);
console.log('\n=== FINAL GRAPH STATS ===');
console.log('Total concepts:', sortedWords.length);
console.log('Total connections:', totalConns);
console.log('Avg connections/word:', (totalConns / sortedWords.length).toFixed(1));
console.log('Unidirectional:', unidir);
console.log('Connectivity:', visited.size + '/' + sortedWords.length, 'reachable');
console.log('\nGroups:', JSON.stringify(groups, null, 2));
